FROM node:20-alpine
WORKDIR /app
COPY ./../backend/package.json ./
RUN npm install --production
COPY ./../backend/src ./src
COPY ./../backend/.env.example ./.env
EXPOSE 5000
CMD ["node", "src/index.js"]
