FROM node:20-alpine
WORKDIR /app
COPY ./../frontend/package.json ./
RUN npm install --production
COPY ./../frontend/src ./src
COPY ./../frontend/public ./public
EXPOSE 3000
CMD ["npx", "react-scripts", "start"]
